version: "3.9"

services:
  crdb:
    image: cockroachdb/cockroach:v21.2.3
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure --listen-addr=0.0.0.0

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  factorial-metrics:
    image: ghcr.io/hryuk/factorial-metrics-local:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: "postgresql://root@crdb:26257/defaultdb?sslmode=disable"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      APP_HTTP_URL: "http://localhost:3000/graphql"
      APP_WS_URL: "ws://localhost:3000/graphql"
