name: Build Docker image and deploy to Kubernetes

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/hryuk/factorial-metrics:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set Kubernetes deployment image
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/factorial-metrics factorial-metrics=ghcr.io/hryuk/factorial-metrics:latest@${{ steps.docker_build.outputs.digest }}

      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: rollout status deployment/factorial-metrics
